// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace com.softpine.muvany.models.Entities.EntitiesIdentity
{
    public partial class Acciones
    {
        public Acciones()
        {
            Permisos = new HashSet<Permisos>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public int? Estado { get; set; }

        public virtual ICollection<Permisos> Permisos { get; set; }
    }
}