// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace com.softpine.muvany.models.Entities.EntitiesIdentity
{
    public partial class AuditLogsIdentity
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Tipo { get; set; }
        public string NombreTabla { get; set; }
        public DateTime? Fecha { get; set; }
        public string ValoresAnteriores { get; set; }
        public string ValoresNuevos { get; set; }
        public string ColumnasAfectadas { get; set; }
        public string PrimaryKey { get; set; }
    }
}