// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace com.softpine.muvany.models.Entities.EntitiesIdentity
{
    public partial class Endpoints
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Controlador { get; set; }
        public string Metodo { get; set; }
        public string HttpVerbo { get; set; }
        public bool Estado { get; set; }

        public virtual EndpointsPermisos EndpointsPermisos { get; set; }
    }
}