// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace com.softpine.muvany.models.Entities.EntitiesIdentity
{
    public partial class EntidadIdentity
    {
        public EntidadIdentity()
        {
            
        }

        public string CodigoEntidad { get; set; }
        public int? CodigoRelacionado { get; set; }
        public string Nombre { get; set; }
        public string RncNo { get; set; }

        
    }
}
