// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace com.softpine.muvany.models.Entities.EntitiesIdentity
{
    public partial class Modulos
    {
        public Modulos()
        {
            Recursos = new HashSet<Recursos>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public int? Estado { get; set; }
        public int? ModuloPadre { get; set; }
        public Modulos? ModuloPadreNav { get; set; }
        public int? OrdenMenu { get; set; }
        public string Cssicon { get; set; }

        public virtual ICollection<Recursos> Recursos { get; set; }
    }
}
