// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace com.softpine.muvany.models.Entities.EntitiesIdentity
{
    public partial class Permisos
    {
        public Permisos()
        {
            EndpointsPermisos = new HashSet<EndpointsPermisos>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int IdAccion { get; set; }
        public int IdRecurso { get; set; }
        public int? EsBasico { get; set; }

        public virtual Acciones IdAccionNavigation { get; set; }
        public virtual Recursos IdRecursoNavigation { get; set; }
        public virtual ICollection<EndpointsPermisos> EndpointsPermisos { get; set; }
    }
}