// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace com.softpine.muvany.models.EntitiesViews;

/// <summary>
/// 
/// </summary>
public partial class UvwUsuariosDominio
{
    /// <summary>
    /// 
    /// </summary>
    public string UsuarioNombre { get; set; }
    /// <summary>
    /// 
    /// </summary>
    public string NombreCompleto { get; set; }
    /// <summary>
    /// 
    /// </summary>    
    public string Nombres { get; set; }
    /// <summary>
    /// 
    /// </summary>
    public string Apellidos { get; set; }
    /// <summary>
    /// 
    /// </summary>
    public string Email { get; set; }
    /// <summary>
    /// 
    /// </summary>
    public string CodigoEmpleado { get; set; }
    /// <summary>
    /// 
    /// </summary>
    public string Departamento { get; set; }
    /// <summary>
    /// 
    /// </summary>
    public string Puesto { get; set; }
}
