// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using com.softpine.muvany.models.Entities;
using com.softpine.muvany.models.EntitiesViews;
using Microsoft.EntityFrameworkCore;

namespace com.softpine.muvany.infrastructure.Persistence.EFContexts
{
    public partial class LenderesContext : DbContext
    {
        /// <summary>
        /// 
        /// </summary>
        public LenderesContext()
        {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="options"></param>
        public LenderesContext(DbContextOptions<LenderesContext> options)
            : base(options)
        {
        }

      
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<ReferenciaUsuarios> ReferenciaUsuarios { get; set; }
      /// <summary>
      /// 
      /// </summary>
      /// <param name="modelBuilder"></param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {  

    
            modelBuilder.Entity<UvwUsuariosDominio>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("Uvw_UsuariosDominio");

                entity.Property(e => e.Apellidos).HasMaxLength(4000);

                entity.Property(e => e.CodigoEmpleado).HasMaxLength(4000);

                entity.Property(e => e.Departamento).HasMaxLength(4000);

                entity.Property(e => e.Email).HasMaxLength(4000);

                entity.Property(e => e.NombreCompleto).HasMaxLength(4000);

                entity.Property(e => e.Nombres).HasMaxLength(4000);

                entity.Property(e => e.Puesto).HasMaxLength(4000);

                entity.Property(e => e.UsuarioNombre).HasMaxLength(4000);
            });





         
            OnModelCreatingPartial(modelBuilder);
        }



        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
