// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace com.softpine.muvany.models.Entities
{
    public partial class ParametrosServidorEmail
    {
        public int Id { get; set; }
        public string Remitente { get; set; }
        public string Host { get; set; }
        public string Puerto { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public int? Estado { get; set; }
    }
}